services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - TZ=America/New_York
      - N8N_HOST=n8n.home.arpa
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://end-screensaver-notes-may.trycloudflare.com/
    container_name: n8n
    restart: unless-stopped
    volumes:
      - ./data:/home/node/.n8n
    networks:
      - homelab
    labels:
      caddy: n8n.home.arpa
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 5678}}"

networks:
  homelab:
    external: true
