services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.home.arpa
    volumes:
      - ./data:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homelab
    labels:
      caddy: home.home.arpa
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  homelab:
    external: true
