.PHONY: build init-db run-all rebuild check dev

build:
	./scripts/build.sh

init-db:
	./scripts/init-db.sh

run-all:
	./scripts/run-all.sh

rebuild:
	./scripts/rebuild-and-run.sh

check:
	./scripts/check-output.sh

dev:
	./scripts/dev-cycle.sh
