services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /storage/lidarr/config:/config
      - /storage/media/music:/music
      - /storage/downloads:/downloads
    networks:
      - homelab
    labels:
      caddy: lidarr.home.arpa
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 8686}}"

networks:
  homelab:
    external: true
